In [62]:
import pandas as pd

In [63]:
reviews = pd.read_csv('/Users/dinarakarakulova/Documents/Msc_CoBi/Machine Learning/Project_ML_SS2025-2/Data/reviews.csv.gz', compression= 'gzip')

In [64]:
listings = pd.read_csv('/Users/dinarakarakulova/Documents/Msc_CoBi/Machine Learning/Project_ML_SS2025-2/Preprocessing/listings_cleaned.csv')

In [65]:
listings.columns

Index(['id', 'listing_url', 'scrape_id', 'source', 'name', 'description',
       'picture_url', 'host_id', 'host_url', 'host_name', 'host_since',
       'host_location', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'has_availability', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm',
       'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly',
       'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'bathrooms_type'],
      dtype='object')

In [66]:
listings['id']

0                      6624
1                     27116
2                     44527
3                     47383
4                     49656
               ...
4556    1349238669235464370
4557    1349336283390581473
4558    1349404120470429129
4559    1363032277989558235
4560    1358916128017498979
Name: id, Length: 4561, dtype: int64

In [67]:
a = listings.loc[listings['id'] == 6624]
b = a[['id','price']]
b

     id  price
0  6624  227.0

In [73]:
id_prices = listings[['id', 'price']]
id_prices = id_prices.rename(columns={'id': 'listing_id'})
id_prices

               listing_id  price
0                    6624  227.0
1                   27116  187.0
2                   44527  391.0
3                   47383   98.0
4                   49656  101.0
...                   ...    ...
4556  1349238669235464370   26.0
4557  1349336283390581473   50.0
4558  1349404120470429129  151.0
4559  1363032277989558235   85.0
4560  1358916128017498979   73.0

[4561 rows x 2 columns]

In [69]:
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,6624,581824,2011-09-29,1189528,Lawrence,The apartment was wonderful and despite our de...
1,6624,654634,2011-10-23,71925,Helen & Rob,This is truly the best place to be. A very nic...
2,6624,2774855,2012-11-01,1570645,Linda,This was a great location and such wonderful p...
3,6624,2987711,2012-11-28,4041941,Joseph,Your apartment gave us a home in Venice...maki...
4,6624,5385172,2013-06-27,743472,Steve And Serenella,"Very nicely and tastefully furnished, clean ..."

In [74]:
reviews = reviews.join(id_prices.set_index('listing_id'), on='listing_id')

ValueError: columns overlap but no suffix specified: Index(['price'], dtype='object')

In [71]:
reviews

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,6624,581824,2011-09-29,1189528,Lawrence,The apartment was wonderful and despite our de...
1,6624,654634,2011-10-23,71925,Helen & Rob,This is truly the best place to be. A very nic...
2,6624,2774855,2012-11-01,1570645,Linda,This was a great location and such wonderful p...
3,6624,2987711,2012-11-28,4041941,Joseph,Your apartment gave us a home in Venice...maki...
4,6624,5385172,2013-06-27,743472,Steve And Serenella,"Very nicely and tastefully furnished, clean ..."
...,...,...,...,...,...,...
758703,1358916128017498979,1364407866305945786,2025-02-25,363237950,경애,Thank you so much the house was very clean and...
758704,1358916128017498979,1366653682781719889,2025-02-28,37316223,Amanda,Thomas notre hote a ete super sympa très actif...
758705,1358916128017498979,1367342365923193755,2025-03-01,651247976,Hyeonjung,"This was the safest, largest, and cleanest pla..."
758706,1361599240863979345,1362993430149075671,2025-02-23,680169572,Mao,It was very convenient because it is located n...
758707,1363032277989558235,1366663268894426098,2025-02-28,114000747,Yazmin,Très bon séjour juste à côté de la plaza San M...

In [59]:
reviews.to_csv('reviews_priced.csv', index = False)

In [60]:
r = pd.read_csv('/Users/dinarakarakulova/Documents/Msc_CoBi/Machine Learning/Project_ML_SS2025-2/Data/reviews_priced.csv')

In [61]:
r.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,6624,581824,2011-09-29,1189528,Lawrence,The apartment was wonderful and despite our de...
1,6624,654634,2011-10-23,71925,Helen & Rob,This is truly the best place to be. A very nic...
2,6624,2774855,2012-11-01,1570645,Linda,This was a great location and such wonderful p...
3,6624,2987711,2012-11-28,4041941,Joseph,Your apartment gave us a home in Venice...maki...
4,6624,5385172,2013-06-27,743472,Steve And Serenella,"Very nicely and tastefully furnished, clean ..."